# -*- coding: utf-8 -*-
"""Projeto_PLN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fLmc4bzGc6Bas7Dk7X1NDy2PZvdFRuB
"""

# =====================================================================
# FASE 0: CONFIGURAÇÃO DE AMBIENTE E DEPENDÊNCIAS
# =====================================================================
print("Configurando ambiente e instalando dependências de PLN...")
!pip install -q wordcloud networkx pyvis spacy nltk scikit-learn gensim
!python -m spacy download pt_core_news_sm -q

# Supressão de avisos não críticos para manter o output do notebook limpo
import warnings
warnings.filterwarnings('ignore')

# 1. Bibliotecas Padrão do Python
import os
import re
from collections import Counter

# 2. Manipulação de Dados e Computação Científica
import numpy as np
import pandas as pd

# 3. Processamento de Linguagem Natural (PLN)
import nltk
from nltk.corpus import stopwords
from nltk.stem import RSLPStemmer
import spacy
from spacy import displacy
from gensim.models import Word2Vec

# 4. Machine Learning (Scikit-Learn)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.manifold import TSNE

# 5. Visualização de Dados e Redes Complexas
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import seaborn as sns
from wordcloud import WordCloud
import networkx as nx

# 6. Integração de Ambiente (Google Colab)
from google.colab import drive

# =====================================================================
# INICIALIZAÇÃO DE PARÂMETROS E MOTORES LINGUÍSTICOS
# =====================================================================
# Download silencioso dos recursos do NLTK
nltk.download('stopwords', quiet=True)
nltk.download('rslp', quiet=True)
nltk.download('punkt', quiet=True)

# Configuração global de estilo e dimensão para os gráficos
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = [10, 6]

print("Ambiente inicializado e bibliotecas carregadas com sucesso.")

# =====================================================================
# FASE 0: CARREGAMENTO DA BASE E FILTRAGEM DO CORPUS
# =====================================================================

# Conexão com o diretório
drive.mount('/content/drive')

print("Carregando a base de dados original...")
caminho_base = '/content/drive/MyDrive/articles.csv'
df_bruto = pd.read_csv(caminho_base)

print(f"Total de registros carregados: {df_bruto.shape[0]}")

# Filtragem do domínio de interesse
filtro_flamengo = df_bruto['text'].str.contains('flamengo', case=False, na=False) | \
                  df_bruto['title'].str.contains('flamengo', case=False, na=False)

df_fla = df_bruto[filtro_flamengo].copy()

# Filtragem de qualidade (documentos com mais de 150 palavras)
df_fla['word_count'] = df_fla['text'].apply(lambda x: len(str(x).split()))
df_fla = df_fla[df_fla['word_count'] > 150]

# Resumo da consolidação do corpus
print("-" * 50)
print("Resumo do Corpus Filtrado (Flamengo):")
print(f"Total de documentos válidos: {len(df_fla)}")
print(f"Média de palavras por documento: {df_fla['word_count'].mean():.1f}")
print("-" * 50)

# =====================================================================
# FASE 1: PRÉ-PROCESSAMENTO E NORMALIZAÇÃO DE TEXTO
# =====================================================================

nlp = spacy.load('pt_core_news_sm')
stop_spacy = nlp.Defaults.stop_words
stop_nltk = set(stopwords.words('portuguese'))

# Remoção de ruídos de formatação e gramática básica
stop_custom = {
    'uol', 'folha', 's.paulo', 'uol.com.br', 'link', 'reportagem',
    'jornal', 'foto', 'o', 'a', 'os', 'as', 'de', 'do', 'da', 'dos',
    'das', 'em', 'no', 'na', 'nos', 'nas', 'por', 'para', 'com', 'que',
    'esse', 'essa', 'esses', 'essas', 'este', 'esta', 'estes', 'estas',
    'isso', 'isto', 'aquilo', 'um', 'uma', 'uns', 'umas', 'seu', 'sua',
    'seus', 'suas', 'ao', 'aos', 'pelo', 'pela', 'pelos', 'pelas',
    'ele', 'ela', 'eles', 'elas', 'mas', 'ou', 'se', 'neste', 'nesta',
    'nesse', 'nessa', 'outro', 'outra', 'outros', 'outras', 'ser',
    'ter', 'fazer', 'ainda', 'sobre', 'após', 'hoje', 'ontem', 'agora',
    'já', 'não'
}

# Remoção de jargões genéricos de domínio (esporte)
stop_futebol = {
    'jogo', 'time', 'clube', 'partida', 'brasileiro', 'paulo', 'rio',
    'futebol', 'equipe', 'jogador', 'ano', 'dia', 'campo', 'vez', 'campeonato'
}

# Remoção de verbos de transição frequentes no jornalismo
stop_contexto = {
    'ficar', 'chegar', 'passar', 'receber', 'levar',
    'marcar', 'ganhar', 'perder', 'conseguir',
    'afirmar', 'dizer', 'falar', 'começar',
    'entrar', 'sair', 'voltar', 'deixar'
}

# Remoção do termo alvo e sinônimos para evitar viés na contagem temática
stop_alvo = {
    'flamengo', 'mengão', 'rubro', 'negro', 'rubro-negro', 'fla'
}

# Consolidação final de stopwords
stops_finais = {p.lower() for p in stop_nltk | stop_spacy | stop_custom | stop_futebol | stop_contexto | stop_alvo}

def preprocessar_texto(texto):
    """Aplica lematização, remoção de pontuação, URLs e stopwords personalizadas."""
    texto = str(texto).lower()
    texto = re.sub(r'http\S+|www\S+|https\S+', '', texto)
    doc = nlp(texto)

    tokens = []
    for t in doc:
        if not t.is_punct and not t.is_digit and not t.is_space:
            lema = t.lemma_.lower().strip()

            if lema == '' or lema == '-pron-':
                lema = t.text.lower().strip()

            txt_orig = t.text.lower().strip()

            if lema not in stops_finais and txt_orig not in stops_finais:
                if len(lema) > 2 and lema.isalpha():
                    tokens.append(lema)

    return tokens

print("Aplicando pipeline de pré-processamento (lematização e filtragem)...")
df_fla['tokens_auditados'] = df_fla['text'].apply(preprocessar_texto)


# =====================================================================
# FASE 1.1: ANÁLISE EXPLORATÓRIA E VISUALIZAÇÃO
# =====================================================================
lista_palavras = [p for lista in df_fla['tokens_auditados'] for p in lista]
dicionario = Counter(lista_palavras)

print("-" * 50)
print("TOP 15 TERMOS MAIS FREQUENTES (CORPUS FLAMENGO):")
for palavra, qtd in dicionario.most_common(15):
    print(f" - {palavra}: {qtd} ocorrências")
print("-" * 50)

plt.figure(figsize=(18, 6))

plt.subplot(1, 2, 1)
sns.histplot(df_fla['word_count'], bins=30, kde=True, color='crimson')
plt.title('Distribuição de Tamanho dos Documentos', fontsize=14, fontweight='bold')
plt.xlabel('Contagem de Palavras')
plt.ylabel('Frequência')

plt.subplot(1, 2, 2)
wordcloud = WordCloud(
    width=800,
    height=500,
    background_color='black',
    colormap='Reds',
    max_words=100
).generate_from_frequencies(dicionario)

plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Nuvem de Palavras (Semântica do Corpus)', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

# =====================================================================
# ANÁLISE MORFOLÓGICA COM POS TAGGING (spaCy)
# =====================================================================
print("\nExecutando Análise Morfológica via POS Tagging (Extração de Adjetivos)...")

# Amostragem aleatória de documentos para otimização de processamento em memória
amostra_pos = df_fla['text'].dropna().sample(n=300, random_state=42).tolist()
adjetivos_corpus = []

for texto in amostra_pos:
    # Limitação do escopo de leitura (primeiros 1500 caracteres) para eficiência computacional
    doc_pos = nlp(texto[:1500])

    for token in doc_pos:
        # Filtragem estrita da classe gramatical 'Adjetivo' (POS = ADJ) e tamanho mínimo
        if token.pos_ == 'ADJ' and len(token.text) > 3:
            adjetivos_corpus.append(token.lemma_.lower())

top_adjetivos = Counter(adjetivos_corpus).most_common(10)

print("-" * 60)
print("TOP 10 ADJETIVOS MAIS FREQUENTES (POS TAGGING)")
print("-" * 60)

for adj, qtd in top_adjetivos:
    print(f" - {adj.capitalize():<15} | Frequência: {qtd}")

print("-" * 60)
print("SÍNTESE DO POS TAGGING:")
print("A predominância de termos avaliativos ('grande', 'bom', 'novo') e numerais/temporais ")
print("('primeiro', 'último') evidencia uma narrativa jornalística focada em ranqueamento, ")
print("qualificação de desempenho e marcos temporais, típicos da crônica esportiva.")

# =====================================================================
# ANÁLISE COMPARATIVA: STEMMING vs LEMMATIZATION
# =====================================================================

print("-" * 60)
print("ANÁLISE COMPARATIVA: STEMMING vs. LEMMATIZATION")
print("-" * 60)

frase_teste = "Os jogadores flamenguistas jogaram e venceram a partida sofrida"
doc_teste = nlp(frase_teste)
stemmer = RSLPStemmer()

dados_comparativos = []

for token in doc_teste:
    if not token.is_punct and not token.is_space:
        original = token.text
        stem = stemmer.stem(original)
        lema = token.lemma_
        dados_comparativos.append({
            'Token Original': original,
            'Stemming (NLTK)': stem,
            'Lematização (spaCy)': lema
        })

df_comparativo = pd.DataFrame(dados_comparativos)
print(df_comparativo.to_string(index=False))

# =====================================================================
# FASE 2: VETORIZAÇÃO (TF-IDF) E BUSCA SEMÂNTICA
# =====================================================================

print("Convertendo documentos em Matriz Numérica Esparsa (TF-IDF)...")
df_fla['texto_tfidf'] = df_fla['tokens_auditados'].apply(lambda x: ' '.join(x))

vetorizador = TfidfVectorizer(max_features=5000)
matriz_tfidf = vetorizador.fit_transform(df_fla['texto_tfidf'])

print(f"Matriz TF-IDF gerada: {matriz_tfidf.shape[0]} documentos e {matriz_tfidf.shape[1]} features.\n")

def buscar_noticias(termo_busca, top_n=3):
    tokens_busca = preprocessar_texto(termo_busca)
    query_limpa = ' '.join(tokens_busca)

    vetor_busca = vetorizador.transform([query_limpa])

    similaridades = cosine_similarity(vetor_busca, matriz_tfidf).flatten()
    indices_top = similaridades.argsort()[::-1][:top_n]

    print(f"Consulta: '{termo_busca}'")
    print("-" * 60)
    for i, idx in enumerate(indices_top):
        score = similaridades[idx]
        if score > 0:
            print(f"{i+1}º Lugar (Similaridade: {score:.1%})")
            print(f"Título: {df_fla['title'].iloc[idx]}")
            print(f"Trecho: {df_fla['text'].iloc[idx][:150]}...\n")
        else:
            print("Nenhum documento relevante encontrado.")
            break

# =====================================================================
# FASE 2.1: EMBEDDINGS DE CONTEXTO (Word2Vec)
# =====================================================================

print("Treinando modelo de Embeddings Contínuos (Word2Vec)...")
modelo_w2v = Word2Vec(
    sentences=df_fla['tokens_auditados'],
    vector_size=100,
    window=5,
    min_count=5,
    workers=4
)

palavra_teste = 'técnico'
if palavra_teste in modelo_w2v.wv:
    print(f"\nTermos semanticamente próximos a '{palavra_teste}':")
    for termo, score in modelo_w2v.wv.most_similar(palavra_teste, topn=5):
        print(f" - {termo} (Score: {score:.1%})")


# =====================================================================
# TESTES DE BUSCA E GRÁFICO t-SNE (Avançado)
# =====================================================================
print("\nExecutando consultas de validação no Motor de Busca Textual...")
buscar_noticias("polêmica e demissão de técnico no campeonato", top_n=1)
buscar_noticias("contratação milionária de atacante da europa", top_n=1)
buscar_noticias("protesto da torcida organizada no aeroporto", top_n=1)

print("Gerando projeção t-SNE rica dos vetores semânticos...")

# Definindo grupos temáticos estruturados para colorir o gráfico
grupos_tematicos = {
    'Comissão Técnica': (['técnico', 'treinador', 'tite', 'muricy', 'comando', 'treino'], 'blue'),
    'Eventos de Jogo': (['gol', 'vitória', 'derrota', 'empate', 'pênalti', 'zagueiro', 'atacante'], 'green'),
    'Ambiente e Torcida': (['estádio', 'torcida', 'maracanã', 'público', 'ingresso', 'festa', 'protesto'], 'darkorange'),
    'Gestão e Mercado': (['presidente', 'diretoria', 'contrato', 'salário', 'milhão', 'proposta', 'reforço'], 'purple'),
    'Rivais e Clubes': (['palmeiras', 'corinthians', 'vasco', 'fluminense', 'botafogo', 'santos'], 'red')
}

vetores = []
palavras_plot = []
cores_plot = []

# Mapeia os vetores apenas se a palavra existir no vocabulário aprendido pela IA
for tema, (palavras, cor) in grupos_tematicos.items():
    for p in palavras:
        if p in modelo_w2v.wv:
            vetores.append(modelo_w2v.wv[p])
            palavras_plot.append(p)
            cores_plot.append(cor)

# Configurando o t-SNE para o novo volume de dados
tsne = TSNE(n_components=2, random_state=42, perplexity=8)
vetores_2d = tsne.fit_transform(np.array(vetores))

# Renderização gráfica
plt.figure(figsize=(14, 9))

for i, palavra in enumerate(palavras_plot):
    plt.scatter(vetores_2d[i, 0], vetores_2d[i, 1], color=cores_plot[i], s=120, edgecolors='black', alpha=0.8)
    plt.text(vetores_2d[i, 0]+0.4, vetores_2d[i, 1]+0.4, palavra, fontsize=11, fontweight='bold', alpha=0.9)

# Criando a legenda customizada
elementos_legenda = [Line2D([0], [0], marker='o', color='w', markerfacecolor=cor, markersize=12, label=tema)
                     for tema, (_, cor) in grupos_tematicos.items()]

plt.legend(handles=elementos_legenda, loc='best', title="Contextos Semânticos (Word2Vec)", title_fontsize='12', fontsize='11')
plt.title("Projeção t-SNE: Agrupamento Semântico de Entidades no Futebol", fontsize=16, fontweight='bold')
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# =====================================================================
# FASE 3: MODELAGEM PREDITIVA E CLASSIFICAÇÃO
# =====================================================================

print("\nPreparando features e variável-alvo para classificação...")
contagem_categorias = df_fla['category'].value_counts()
categorias_validas = contagem_categorias[contagem_categorias >= 10].index

filtro_ml = df_fla['category'].isin(categorias_validas)
X = matriz_tfidf[filtro_ml.values]
y = df_fla[filtro_ml]['category']

print(f"Distribuição das classes para treinamento:\n{y.value_counts()}\n")

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print("Iniciando treinamento e avaliação dos modelos classificadores...")
modelos = {
    "Naive Bayes": MultinomialNB(),
    "Regressão Logística": LogisticRegression(max_iter=1000, random_state=42),
    "SVM": SVC(kernel='linear', class_weight='balanced', random_state=42)
}

melhor_modelo = ""
melhor_acuracia = 0
y_pred_campeao = None

for nome, modelo in modelos.items():
    modelo.fit(X_treino, y_treino)
    previsoes = modelo.predict(X_teste)

    acuracia = accuracy_score(y_teste, previsoes)

    print(f"Acurácia - {nome}: {acuracia:.1%}")

    if acuracia > melhor_acuracia:
        melhor_acuracia = acuracia
        melhor_modelo = nome
        y_pred_campeao = previsoes

print("-" * 60)
print(f"Melhor Modelo Identificado: {melhor_modelo} (Acurácia: {melhor_acuracia:.1%})")
print("-" * 60)


# =====================================================================
# FASE 3.1: AVALIAÇÃO DE DESEMPENHO E MATRIZ DE CONFUSÃO
# =====================================================================
print("\nRelatório de Classificação (Classification Report):")
print(classification_report(y_teste, y_pred_campeao, zero_division=0))

plt.figure(figsize=(10, 6))
matriz_confusao = confusion_matrix(y_teste, y_pred_campeao)
sns.heatmap(matriz_confusao, annot=True, fmt='d', cmap='Blues',
            xticklabels=modelos[melhor_modelo].classes_,
            yticklabels=modelos[melhor_modelo].classes_)

plt.title(f'Matriz de Confusão - Modelo: {melhor_modelo}', fontsize=14, fontweight='bold')
plt.ylabel('Categoria Real', fontsize=12)
plt.xlabel('Categoria Predita', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# =====================================================================
# FASE 4: EXTRAÇÃO DE ENTIDADES (NER) E GRAFOS
# =====================================================================

print("\nIniciando Extração de Entidades Nomeadas (NER)...")
amostra_textos = df_fla['text'].dropna().sample(n=500, random_state=42).tolist()
entidades_extraidas = []

for texto in amostra_textos:
    doc = nlp(texto[:3000])
    for entidade in doc.ents:
        if entidade.label_ in ['PER', 'ORG', 'LOC']:
            nome = entidade.text.strip().title()
            if len(nome) > 3 and nome.lower() not in ['flamengo', 'fla']:
                entidades_extraidas.append(nome)

top_entidades = Counter(entidades_extraidas).most_common(25)


# =====================================================================
# FASE 4.1: MODELAGEM DO GRAFO E CENTRALIDADE
# =====================================================================
print("Construindo Grafo de Conhecimento e calculando centralidade...")
grafo = nx.Graph()
no_central = "Flamengo"

for entidade, peso in top_entidades:
    grafo.add_edge(no_central, entidade, weight=peso)

centralidade = nx.degree_centrality(grafo)

centralidade_sem_fla = {no: grau for no, grau in centralidade.items() if no != no_central}
top_central = sorted(centralidade_sem_fla.items(), key=lambda x: x[1], reverse=True)[:3]

print("\n" + "-" * 60)
print("SÍNTESE ANALÍTICA DO GRAFO:")
print(f"Estrutura Topológica: {grafo.number_of_nodes()} nós e {grafo.number_of_edges()} arestas.")
print("Entidades com maior relevância no ecossistema (Co-ocorrências):")
for nome, grau in top_central:
    peso_aresta = grafo[no_central][nome]['weight']
    print(f" - {nome} (Peso: {peso_aresta})")
print("-" * 60)


# =====================================================================
# FASE 4.2: VISUALIZAÇÃO DO GRAFO
# =====================================================================
plt.figure(figsize=(14, 10))
posicao = nx.spring_layout(grafo, k=0.8, seed=42)

pesos = [grafo[no_central][no]['weight'] * 15 if no != no_central else 3000 for no in grafo.nodes()]
cores = ['lightgray' if no != no_central else 'crimson' for no in grafo.nodes()]

nx.draw_networkx_nodes(grafo, posicao, node_size=pesos, node_color=cores, alpha=0.9, edgecolors='black')
nx.draw_networkx_edges(grafo, posicao, width=1.5, alpha=0.4, edge_color='gray')
nx.draw_networkx_labels(grafo, posicao, font_size=9, font_weight='bold')

plt.title("Grafo de Conhecimento: Ecossistema de Entidades", fontsize=16, fontweight='bold')
plt.axis('off')
plt.tight_layout()
plt.show()

# =====================================================================
# FASE 5: RENDERIZAÇÃO DE DEPENDÊNCIAS E ENCERRAMENTO
# =====================================================================

print("\nRenderizando amostra de extração NER via displaCy...")

texto_exemplo = "O Flamengo enfrentou o Palmeiras no Maracanã e em São Paulo, sob o olhar atento do Brasil e da Folha de S.Paulo."
doc_exemplo = nlp(texto_exemplo)

displacy.render(doc_exemplo, style="ent", jupyter=True)

print("\nExecução do pipeline finalizada com sucesso.")

# =====================================================================
# GRÁFICOS ADICIONAIS PARA O RELATÓRIO
# =====================================================================

plt.figure(figsize=(16, 6))

# 1. Gráfico de Barras (Top 15 Termos)
plt.subplot(1, 2, 1)
top_palavras = dicionario.most_common(15)
palavras, contagens = zip(*top_palavras)
sns.barplot(x=list(contagens), y=list(palavras), palette="Reds_r")
plt.title('Top 15 Termos Mais Frequentes (Lematizados)', fontsize=14, fontweight='bold')
plt.xlabel('Frequência Absoluta')
plt.ylabel('Termos')

# 2. Gráfico de Desbalanceamento (Variável Alvo)
plt.subplot(1, 2, 2)
contagem_target = df_fla[filtro_ml]['category'].value_counts()
sns.barplot(x=contagem_target.values, y=contagem_target.index, palette="Blues_r")
plt.title('Desbalanceamento de Classes (Variável Target)', fontsize=14, fontweight='bold')
plt.xlabel('Número de Notícias')
plt.ylabel('Categorias do Jornal')

plt.tight_layout()
plt.show()